[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
staking_contract = "9eAYUGAy3JVdDXsqScRAa1ejeDpNjXTQyJ5ALkcdky6h"

[programs.devnet]
staking_contract = "9eAYUGAy3JVdDXsqScRAa1ejeDpNjXTQyJ5ALkcdky6h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whitehorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-staking-contract.ts"
