[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
staking_contract = "ADbv96w7D9argjCubvNbf4oKdCFN8nU6yc4Y8ZDbdHnY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/whitehorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-staking-contract.ts"
